# Generated by Django 2.2 on 2019-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resid',
            name='resname',
            field=models.CharField(default='foobar', max_length=128),
        ),
    ]
