# Generated by Django 2.2 on 2019-11-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewRestaurant', '0003_auto_20191105_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resid',
            name='resname',
        ),
    ]
